name: mobile_app
description: "LAN-Only Personal Music Streaming Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  just_audio: ^0.9.36
  audio_service: ^0.18.15
  http: ^1.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  url_launcher: ^6.3.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo.png"
  min_sdk_android: 21
